name: coffee_repository
description: A .

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=3.1.3 <4.0.0'

dependencies:
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    cart_repository:
        path: ../cart_repository

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

    # database dependencies
    hive_generator:
    build_runner:
